begin;

create or replace function public.count_staff_complaints() returns bigint language sql stable security definer set search_path = public, extensions as $$ select count(*)::bigint from public.complaints c where public.is_active_staff() and (public.current_staff_role() in ('head_department','super_admin') or (public.current_staff_role() = 'supervisor' and (c.assigned_user_id=auth.uid() or c.assigned_department=(select department from public.users where id=auth.uid()) or c.assigned_user_id is null)) or (public.current_staff_role() = 'employee' and c.assigned_user_id=auth.uid())); $$;
revoke all on function public.count_staff_complaints() from public, anon; grant execute on function public.count_staff_complaints() to authenticated;

create or replace function public.list_staff_complaints() returns table(id uuid, tracking_id text, citizen_name text, category text, municipality text, daira text, neighborhood text, subject text, description text, meeting_request text, status text, priority text, assigned_department text, assigned_user_id uuid, deadline timestamptz, official_response jsonb, timeline jsonb, created_at timestamptz, updated_at timestamptz, attachments jsonb) language sql stable security definer set search_path = public as $$ select c.id, c.tracking_id, c.citizen_name, c.category, c.municipality, c.daira, c.neighborhood, c.subject, c.description, c.meeting_request, c.status, c.priority, c.assigned_department, c.assigned_user_id, c.deadline, c.official_response, c.timeline, c.created_at, c.updated_at, case when jsonb_typeof(c.attachments)='array' then c.attachments else '[]'::jsonb end from public.complaints c where public.is_active_staff() and (public.current_staff_role() in ('head_department','super_admin') or (public.current_staff_role() = 'supervisor' and (c.assigned_user_id=auth.uid() or c.assigned_department=(select department from public.users where id=auth.uid()) or c.assigned_user_id is null)) or (public.current_staff_role() = 'employee' and c.assigned_user_id=auth.uid())) order by c.created_at desc limit 1000; $$;
revoke all on function public.list_staff_complaints() from public, anon; grant execute on function public.list_staff_complaints() to authenticated;

commit;
